name: CI test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:15-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis:7.0-alpine
        ports:
          - 6379:6379

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.3
        id: go

      - name: Checkout code into the Go module directory
        uses: actions/checkout@v3

      - name: Install golang-migrate
        run: |
          go install github.com/rubenv/sql-migrate/...@latest
      - name: Run migrations
        run: make migrateup

      - name: Test
        run: make test
