version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=loose_style
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
  api:
    container_name: golang_api
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - postgres:postgres
      - redis:redis
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
    command: ["/app/main"]
