version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command:
      - redis-server --appendonly yes

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@localhost:5432/loose_style?sslmode=disable
      - REDIS_SOUCE="redis://root:secret>@localhost:6379/loose_style_redis?sslmode=disable"
    depends_on:
      - postgres
      - redis
    entrypoint: ["redis:6379", "postgres:5432"]
    command: ["/app/main"]
