// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: adminUser.sql

package db

import (
	"context"
	"time"
)

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO adminuser(
    username, password, created_at
) VALUES (
    $1, $2, $3
) RETURNING id, username, password, created_at
`

type CreateAdminUserParams struct {
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (*Adminuser, error) {
	row := q.db.QueryRow(ctx, createAdminUser, arg.Username, arg.Password, arg.CreatedAt)
	var i Adminuser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
	)
	return &i, err
}

const getAdminUser = `-- name: GetAdminUser :one
SELECT id, username, password, created_at FROM adminuser WHERE username = $1 AND password = $2
`

type GetAdminUserParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

func (q *Queries) GetAdminUser(ctx context.Context, arg GetAdminUserParams) (*Adminuser, error) {
	row := q.db.QueryRow(ctx, getAdminUser, arg.Username, arg.Password)
	var i Adminuser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
	)
	return &i, err
}
