// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: carts.sql

package db

import (
	"context"
)

const createCartItem = `-- name: CreateCartItem :one
INSERT INTO carts (
    user_id, product_id
) VALUES (
    $1, $2
) RETURNING id, user_id, product_id
`

type CreateCartItemParams struct {
	UserID    int64 `json:"user_id"`
	ProductID int64 `json:"product_id"`
}

func (q *Queries) CreateCartItem(ctx context.Context, arg CreateCartItemParams) (*Carts, error) {
	row := q.db.QueryRow(ctx, createCartItem, arg.UserID, arg.ProductID)
	var i Carts
	err := row.Scan(&i.ID, &i.UserID, &i.ProductID)
	return &i, err
}

const deleteCartItem = `-- name: DeleteCartItem :exec
DELETE FROM carts
WHERE id = $1
`

func (q *Queries) DeleteCartItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCartItem, id)
	return err
}

const getAllCartItem = `-- name: GetAllCartItem :many
SELECT p.id, p.product_name, p.description, p.img, p.unit_price, p.discount, p.stock, p.brand_id, p.category, p.created_at, p.updated_at FROM carts AS c
INNER JOIN users AS u ON c.user_id = u.id
INNER JOIN products AS p ON c.product_id = p.id
WHERE c.user_id = $1
`

func (q *Queries) GetAllCartItem(ctx context.Context, userID int64) ([]*Products, error) {
	rows, err := q.db.Query(ctx, getAllCartItem, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Products{}
	for rows.Next() {
		var i Products
		if err := rows.Scan(
			&i.ID,
			&i.ProductName,
			&i.Description,
			&i.Img,
			&i.UnitPrice,
			&i.Discount,
			&i.Stock,
			&i.BrandID,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
