// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Adminuser struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
}

type Brands struct {
	ID        int64  `json:"id"`
	BrandName string `json:"brand_name"`
}

type Carts struct {
	ID        int64 `json:"id"`
	UserID    int64 `json:"user_id"`
	ProductID int64 `json:"product_id"`
}

type Categories struct {
	ID       int64  `json:"id"`
	Category string `json:"category"`
}

type Media struct {
	ID        int64     `json:"id"`
	Title     string    `json:"title"`
	Contents  string    `json:"contents"`
	Img       string    `json:"img"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Orders struct {
	ID        int64     `json:"id"`
	UserID    string    `json:"user_id"`
	ProductID int64     `json:"product_id"`
	Quantity  int32     `json:"quantity"`
	Postage   int32     `json:"postage"`
	Price     int32     `json:"price"`
	Status    bool      `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

type Products struct {
	ID          int64          `json:"id"`
	ProductName string         `json:"product_name"`
	Description sql.NullString `json:"description"`
	Img         sql.NullString `json:"img"`
	UnitPrice   int32          `json:"unit_price"`
	Discount    float64        `json:"discount"`
	Stock       int32          `json:"stock"`
	BrandID     int64          `json:"brand_id"`
	Category    int64          `json:"category"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Users struct {
	ID                    int64     `json:"id"`
	UserID                string    `json:"user_id"`
	Password              string    `json:"password"`
	Username              string    `json:"username"`
	Email                 string    `json:"email"`
	Sex                   string    `json:"sex"`
	DataOfBirth           string    `json:"data_of_birth"`
	DestinationFamilyName string    `json:"destination_family_name"`
	DestinationFirstName  string    `json:"destination_first_name"`
	Postcode              int32     `json:"postcode"`
	PrefectureCode        string    `json:"prefecture_code"`
	City                  string    `json:"city"`
	Street                string    `json:"street"`
	Building              string    `json:"building"`
	Phone                 string    `json:"phone"`
	CreatedAt             time.Time `json:"created_at"`
	UpdatedAt             time.Time `json:"updated_at"`
}
